[package]
name = "dynamix"
version = "0.1.0"
edition = "2021"

[lib]
name = "dynamix"
path = "src/lib.rs"

[features]
stack-trace = []

default = ["stack-trace"]

[[bin]]
name = "testbed"
path = "src/bin.rs"

[dependencies]
